---
sidebar: sidebar 
permalink: rn/known_issues.html 
keywords: known issues, issues, bugs, fixes 
summary: Sie sollten alle bekannten Probleme für die aktuelle Version im Zusammenhang mit der Astra Control REST API überprüfen. Die bekannten Probleme identifizieren Probleme, die die erfolgreiche Verwendung des Produkts verhindern könnten. 
---
= Bekannte Probleme
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie sollten alle bekannten Probleme für die aktuelle Version im Zusammenhang mit der Astra Control REST API überprüfen. Die bekannten Probleme identifizieren Probleme, die die erfolgreiche Verwendung des Produkts verhindern könnten.


NOTE: Es gibt keine neuen bekannten Probleme mit der Version 23.06 der Astra Control REST API. Diese API-Version wird zusammen mit Astra Control Center 23.04 und Astra Control Service 23.06 verwendet. Alle nachfolgend beschriebenen Probleme wurden in vorherigen Versionen entdeckt und gelten weiterhin für die aktuelle Version.

Sehen Sie sich eine der folgenden Seiten auf der Grundlage Ihres Bereitstellungsmodells an.

* https://docs.netapp.com/us-en/astra-control-service/release-notes/known-issues.html["Bekannte Probleme beim Astra Control Service"^]
* https://docs.netapp.com/us-en/astra-control-center-2304/release-notes/known-issues.html["Bekannte Probleme bei Astra Control Center"^]

